Fix failure in deactivate_outdated_results
Commit 739bd03aca1a9d8259d4d87c69ff970d805cc56f introduced a
regression in the deactivate_outdated_results() function, in
particular, clients.py[1] tries to read the Ansible rally.ini.j2 template
as an ini file and jinja2 markup can't be parsed resulting to errors
like:

```
configparser.ParsingError: Source contains parsing errors: '/var/lib/jenkins/night_rally/fixtures/ansible/roles/rally-update/templates/rally.ini.j2'
    [line 41]: '{% raw %}\n'
    [line 50]: '{% endraw %}\n'
```

Fix regression by bringing back the ini style comments where jinja2
markup is used, but don't use whitespace control characters (`-`) to
ensure no real ini file declaration ends up in the same line after a
`#` comment character.

[1]
https://github.com/elastic/night-rally/blob/e6e7daa462b20b210eacf357ee306e03c6ced447/client.py#L10