Fix `make configure` (#712)
We are using a rather old version of Ansible which has issues with more
recent Python versions that we use, resulting in the error:

```
PLAY [Configures Rally locally] ************************************************************************************
[WARNING]: Skipping plugin (/home/dl/source/elastic/night-rally/.venv/lib/python3.8/site-
packages/ansible/plugins/filter/core.py) as it seems to be invalid: cannot import name 'environmentfilter' from
'jinja2.filters' (/home/dl/source/elastic/night-rally/.venv/lib/python3.8/site-packages/jinja2/filters.py)
[WARNING]: Skipping plugin (/home/dl/source/elastic/night-rally/.venv/lib/python3.8/site-
packages/ansible/plugins/filter/mathstuff.py) as it seems to be invalid: cannot import name 'environmentfilter'
from 'jinja2.filters' (/home/dl/source/elastic/night-rally/.venv/lib/python3.8/site-packages/jinja2/filters.py)

TASK [rally-configure : install Rally config file] *****************************************************************
fatal: [localhost]: FAILED! => {"msg": "template error while templating string: No filter named 'bool'.. String: {{ not local_setup | default() | bool }}"}
```

Fix the issue by bumping Ansible to match the version used by esbench.